const StorageKeys = Object.freeze({
  LOGIN_REDIRECT: 'LOGIN_REDIRECT',
  SEEN_MOBILIZE_TOAST: 'SEEN_MOBILIZE_TOAST',
  SESSION_CONTACT_COUNT: 'SESSION_CONTACT_COUNT',
  SESSION_SUCCESS_COUNT: 'SESSION_SUCCESS_COUNT',
  SWITCHBOARD_ADMIN: 'SWITCHBOARD_ADMIN',
  USER_PROFILE: 'USER_PROFILE',
  VOLUNTEER_LEADS: 'VOLUNTEER_LEADS',
});

export default StorageKeys;
